#!/usr/bin/env bash

# montage tile-{0..15}.png -tile 4x4 -geometry +0+0 output.png

if [ "$#" -ne 4 ]; then
  echo "Usage: $0 <file_prefix> <lower_bound> <upper_bound> <grid>"
  echo "Example: $0 globalMap 1 16 4x4"
  echo "Example note: globalMap_0 is an overview image and not a tile therefore combining starts at 1."
  exit 1
fi

if ! command -v montage &> /dev/null; then
  echo "montage command not found. Please install ImageMagick."
  exit 1
fi

file_prefix=$1
lower_bound=$2
upper_bound=$3
grid=$4

files=""
for i in $(seq "$lower_bound" "$upper_bound"); do
    files+=" output-images/${file_prefix}_${i}.PNG"
done

mkdir -p output-combined
montage -monitor $files -tile $grid -geometry +0+0 output-combined/$file_prefix.png