#!/usr/bin/env bash

# montage tile-{0..15}.png -tile 4x4 -geometry +0+0 output.png

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 <grid> <file> [file ...]"
  echo "Example: $0 4x4 globalMap_{1..16}"
  echo "Example note: globalMap_0 is an overview image and not a tile therefore combining starts at 1."
  exit 1
fi

if ! command -v montage &> /dev/null; then
  echo "montage command not found. Please install ImageMagick."
  exit 1
fi

grid=$1
shift

files=""
for f in "$@"; do
    files+=" output-images/${f}.PNG"
done

file_prefix=$(echo "$1" | sed 's/_[0-9]\+$//')
mkdir -p output-combined
montage -monitor $files -tile $grid -geometry +0+0 output-combined/$file_prefix.png