#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <image_name>"
  echo "Example: $0 globalMap"
  exit 1
fi

if ! command -v gdal2tiles.py &> /dev/null; then
  echo "gdal2tiles.py could not be found. Please install it and try again."
  echo "You can install it using 'sudo apt-get install gdal-bin' or 'pip install gdal'."
  exit 1
fi

image_name=$1

input_image="output-combined/$image_name.png"
output_dir="output-tiles/$image_name"
temp_image="$output_dir/$image_name.temp.tif"

mkdir -p "$output_dir"
gdal_translate -a_srs EPSG:3857 "$input_image" "$temp_image"
gdal2tiles.py -z 0-5 -w none -p raster "$temp_image" "$output_dir"
rm "$temp_image"
